artifact_location: /home/cse/rait_session/mlflow_practice/udemy_mlflow/mytracks/0
creation_time: 1728923539089
experiment_id: '0'
last_update_time: 1728923539089
lifecycle_stage: active
name: Default
